name: Docs

on:
  push:
    branches: [main]
    paths:
      - "docs/**"
      - "src/**/*.mdx"
  pull_request:
    paths:
      - "docs/**"
      - "src/**/*.mdx"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install --frozen-lockfile
        working-directory: docs
      - run: bun run build
        working-directory: docs
